import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./Provider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-white dark:bg-black text-black dark:text-white`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Provider>
              {/* Fullscreen layout */}
              <div className="flex flex-col min-h-screen">
                {/* Navbar at top */}
                <Navbar />

                {/* Main content below navbar */}
                <div className="flex flex-1 overflow-hidden">
                  {/* Sidebar can be placed here if it's a permanent side panel */}
                  {/* <SideNav /> */}

                  {/* Page content */}
                  <main className="flex-1 overflow-y-auto p-4">
                    {children}
                  </main>
                </div>
              </div>
            </Provider>
          </ThemeProvider>

          {/* Ionicons Script */}
          <Script
            type="module"
            src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
          />
          <Script
            noModule
            src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
